//defines.h
#define SETBIT(WORD,BITPOS) WORD|=(1<<BITPOS)
#define SSETBIT(WORD,BITPOS) WORD=(1<<BITPOS)
#define SCLRBIT(WORD,BITPOS) WORD=(1<<BITPOS)
#define CLRBIT(WORD,BITPOS) WORD&=(~(1<<BITPOS))
#define WRITEBYTE(WORD,SBITPOS,BYTE) WORD=(WORD&(~(255<<SBITPOS)))|(BYTE<<SBITPOS)
#define READBIT(WORD,BITPOS) ((WORD>>BITPOS)&1)
#define CFGPIN(WORD,PIN,FUNC) WORD=(PIN<16)?((WORD&(~(3<<(PIN*2))))|(FUNC<<(PIN*2))):((WORD&(~(3<<((PIN-16)*2))))|(FUNC<<((PIN-16)*2)))
#define FUN1 0
#define FUN2 1
#define FUN3 2
#define FUN4 3
